# Generated by Django 2.2.9 on 2019-12-31 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usertask',
            constraint=models.UniqueConstraint(fields=('user', 'task'), name='unique_user_task'),
        ),
    ]
